module.exports = [
  {title: "The Lord Of The Rings Trilogy", author_name: "J.R.R. Tolkien", description: "Tolkien's seminal three-volume epic chronicles the War of the Ring, in which Frodo the hobbit and his companions set out to destroy the evil Ring of Power and restore peace to Middle-earth. The beloved trilogy still casts a long shadow, having established some of the most familiar and enduring tropes in fantasy literature.",
    additional: { pages: 1178, list_price: 20}},
  {title: "The Hitchhiker's Guide To The Galaxy", author_name: "Douglas Adams", description: "In the first, hilarious volume of Adams' Hitchhiker's series, reluctant galactic traveler Arthur Dent gets swept up in some literally Earth-shattering events involving aliens, sperm whales, a depressed robot, mice who are more than they seem, and some really, really bad poetry.",
    additional: { pages: 216,  list_price: 6.99}},
  {title: "Ender's Game", author_name: "Orson Scott Card", description: "Young Andrew 'Ender' Wiggin, bred to be a genius, is drafted to Battle School where he trains to lead the century-long fight against the alien Buggers.",
    additional: { pages: 349, list_price: 5.99}},
  {title: "The Dune Chronicles", author_name: "Frank Herbert", description: "Follows the adventures of Paul Atreides, the son of a betrayed duke given up for dead on a treacherous desert planet and adopted by its fierce, nomadic people, who help him unravel his most unexpected destiny.",
    additional: { pages: 535, list_price: 6.50}},
  {title: "A Song Of Ice And Fire Series", author_name: "George R. R. Martin", description: "As the Seven Kingdoms face a generation-long winter, the royal Stark family confronts the poisonous plots of the rival Lannisters, the emergence of the Neverborn demons, the arrival of barbarian hordes, and other threats.",
    additional: { pages: 4228, list_price: 35.96}},
  {title: "1984", author_name: "George Orwell", description: "Portrays life in a future time when a totalitarian government watches over all citizens and directs all activities.",
    additional: { pages: 339, list_price: 15.95}},
  {title: "Fahrenheit 451", author_name: "Ray Bradbury", description: "In a far future world, television dominates, and books are outlawed. The totalitarian regime has ordered all books to be burned by firemen, whose job is to start the fires rather than stop them. But one fireman begins to see the value of the printed word.",
    additional: { pages: 159, list_price: 11.99}},
  {title: "The Foundation Trilogy", author_name: "Isaac Asimov", description: "A band of psychologists, under the leadership of psychohistorian Hari Seldon, plant a colony to encourage art, science, and technology in the declining Galactic Empire and to preserve the accumulated knowledge of humankind.",
    additional: { pages: 255, list_price: 9.50}},
  {title: "Brave New World", author_name: "Aldous Huxley", description: "Huxley's classic prophetic novel describes the socialized horrors of a futuristic utopia devoid of individual freedom.",
    additional: {pages: 20, list_price: 14.99}},
  {title: "American Gods", author_name: "Neil Gaiman", description: "On the plane home to attend the funerals of his wife and best friend, Shadow, an ex-con, encounters an enigmatic stranger who seems to know a lot about him. When Shadow accepts the stranger's job offer, he finds himself plunged into a perilous game with the highest of stakes: the soul of America itself.",
    additional: { pages: 541, list_price: 19.99}},
  {title: "The Princess Bride", author_name: "William Goldman", description: "This tale of a handsome farm boy who, aided by a drunken swordsman and a gentle giant, rescues a beautiful princess named Buttercup comes with a slyly humorous, metafictional edge: Goldman claims to have merely abridged an earlier text by one 'S. Morgenstern' (actually a pseudonym) and peppers his text with clever commentary.",
    additional: { pages: 456, list_price: 8.95}},
  {title: "The Wheel Of Time Series", author_name: "Robert Jordan", description: "At 13 volumes and counting, this sweeping — some would say sprawling – richly imagined epic chronicles the struggle between servants of the Dark One and those of the champion of light known as the Dragon Reborn.",  additional: { pages: 2272, list_price: 20.97}},
  {title: "Animal Farm", author_name: "George Orwell", description: "Farm animals overthrow their human owners and set up their own deeply (and familiarly) flawed government. Orwell's mordant satire of totalitarianism is still a mainstay of ninth-grade reading lists.",
    additional: { pages: 97, list_price: 14}},
  {title: "Neuromancer", author_name: "William Gibson", description: "Gibson's groundbreaking debut novel follows Case, a burned-out computer whiz, who is asked to steal a security code that is locked in the most heavily guarded databank in the solar system. A seminal work in the genre that would come to be known as cyberpunk.",
    additional: { pages: 371, list_price: 25}},
  {title: "Watchmen", author_name: "Alan Moore", description: "As former members of a disbanded group of superheroes called the Crimebusters start turning up dead, the remaining members of the group try to discover the identity of the murderer before they, too, are killed. A graphic novel.",
    additional: { pages: 436, list_price: 39.99}},
  {title: "I, Robot", author_name: "Isaac Asimov", description: "Isaac Asimov changed our perception of robots forever when he formulated the laws governing their behavior. In I, Robot, Asimov chronicles the development of the robot through a series of interlinked stories: from its primitive origins in the present to its ultimate perfection in the not-so-distant future — a future in which humanity itself may be rendered obsolete.",
    additional: { pages: 224, list_price: 15}},
  {title: "Stranger In A Strange Land", author_name: "Robert Heinlein", description: "Valentine Michael Smith, born and raised on Mars, arrives on Earth stunning Western culture with his superhuman abilities.",
    additional: { pages: 525, list_price: 18}},
  {title: "The Kingkiller Chronicles", author_name: "Patrick Rothfuss", description: "This suspenseful coming-of-age story folllows Kvothe as he recounts his transformation from a magically gifted young man into the most notorious wizard, musician, thief and assassin in his world.",
    additional: { pages: 661, list_price: 17}},
  {title: "Slaughterhouse-Five", author_name: "Kurt Vonnegut", description: "Billy Pilgrim returns home from World War II only to be kidnapped by aliens from the planet Tralfamadore, who teach him that time is an eternal present.",
    additional: { pages: 275, list_price: 15}},
  {title: "Frankenstein", author_name: "Mary Shelley", description: "Mary Shelley's chilling portrait of a scientist obsessed with creating life (whose eventual success comes at too great a cost) was among the first works of science fiction ever produced. Its potent allegorical power, compelling ethical and philosophical themes, and its sheer creepiness have ensured it remains one of the most enduring and influential as well.",
    additional: { pages: 166, list_price: 6}},
  {title: "Do Androids Dream Of Electric Sheep?", author_name: "Philip K. Dick", description: "Dick's trippy novel tells of sophisticated off-world androids who turn against their creators, slip back to a post-apocalyptic Earth, and must be hunted down by bounty hunter Rick Deckard. The book inspired — albeit very loosely — the 1982 Ridley Scott film Blade Runner.",
    additional: { pages: 244, list_price: 14}},
  {title: "The Handmaid's Tale", author_name: "Margaret Atwood", description: "A chilling look at the near future presents the story of Offred, a Handmaid in the Republic of Gilead, once the United States, an oppressive world where women are no longer allowed to read and are valued only as long as they are viable for reproduction.",
    additional: { pages: 311, list_price: 15.95}},
  {title: "The Dark Tower Series", author_name: "Stephen King", description: "Roland, the world's last gunslinger, tracks an enigmatic Man in Black toward a forbidding dark tower, fighting forces both mortal and other worldly on his quest.",
    additional: { pages: 231, list_price: 18}},
  {title: "2001: A Space Odyssey", author_name: "Arthur C. Clarke", description: "Two astronauts find their journey into space and their very lives jeopardized by the jealousy of an extraordinary computer named HAL.",
    additional: { pages: 221, list_price: 6.99}},
  {title: "The Stand", author_name: "Stephen King", description: "A monumentally devastating plague leaves only a few survivors who, while experiencing dreams of a battle between good and evil, move toward an actual confrontation as they migrate to Boulder, Colo.",
    additional: { pages: 1439, list_price: 8.99}},
  {title: "Snow Crash", author_name: "Neal Stephenson",    description: `Weaving contemporary imagery with Sumerian myths, Stephenson's third novel revolves around a mysterious "pseudo-narcotic" Snow Crash that is capable of affecting people both within — and without — the alternate-reality Internet called the "Metaverse."`,
    additional: { pages: 470, list_price: 15}},
  {title: "The Martian Chronicles", author_name: "Ray Bradbury", description: "The tranquillity of Mars is disrupted by the earthmen who have come to conquer space, colonize the planet, and escape a doomed Earth.",
    additional: { pages: 268, list_price: 18.99}},
  {title: "Cat's Cradle", author_name: "Kurt Vonnegut", description: "A young writer decides to interview the children of a scientist primarily responsible for the creation of the atomic bomb.",
    additional: { pages: 287, list_price: 15}},
  {title: "The Sandman Series", author_name: "Neil Gaiman", description: "Gaiman originally told his tale of Morpheus, the Dream King, whose interactions with mortals rarely end well, and whose fractious extended family includes the personifications of Death, Despair, Desire and Destiny, in a 75-issue comic book series over several years; the hugely influential series is now collected in ten trade volumes.",
    additional: { pages: 50, list_price: 19.99}}
]